export interface HuePluginConfig {
  /**
   * The hostname or IP address of the Hue bridge.
   *
   * @type {string}
   * @memberof HuePluginConfig
   */
  host: string;
  /**
   * The username generated by the bridge during the pairing procedure.
   *
   * @type {string}
   * @memberof HuePluginConfig
   */
  username: string;
}
